"""emit_compact.py -- compact delta-stream firmware generation.

This is the production-oriented alternative to fully-unrolled SetReg C.
It keeps the control-core .text constant and moves the macro-instruction stream
into HBM, but goes one step beyond the plain interpreter: instead of storing all
16 register words for every instruction, it stores only words that changed since
that core's previous instruction.

Binary layout of program_compact.bin:
  repeated instruction records, grouped by the compile-time wave_len[] table:
    uint32 header = (core_id & 0xff) | (write_mask << 8)
    uint32 values[popcount(write_mask)]  // values in ascending register order

The firmware reads each header, walks bits 0..15 of the mask, and writes only
those registers.  Register values persist across commands, so unchanged fields
need not be re-emitted.  If a previous non-zero word must become zero, the mask
contains that register and the value stream contains 0.
"""
from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from typing import List, Tuple

from . import backend, isa
from .emit_firmware import collect
from .models import PRESETS, build_graph
from .schedule import Scheduler

COMPACT_PROG_BASE = 0x4000000000


def _popcount(x: int) -> int:
    return int(x).bit_count()


def _u32_bytes(x: int) -> bytes:
    return int(x & 0xFFFFFFFF).to_bytes(4, "little")


@dataclass
class CompactProgram:
    raw: bytes
    words: List[int]
    masks: List[int]
    cores: List[int]
    wave_len: List[int]
    n_instr: int
    n_wave: int
    setreg_full: int
    setreg_compact: int
    full_program_bytes: int

    def stats(self) -> dict:
        compact_bytes = len(self.raw)
        return {
            "mode": "compact-delta",
            "n_instr": self.n_instr,
            "n_wave": self.n_wave,
            "full_program_bytes": self.full_program_bytes,
            "compact_program_bytes": compact_bytes,
            "program_saved_pct": round(100.0 * (1.0 - compact_bytes / self.full_program_bytes), 2)
            if self.full_program_bytes else 0.0,
            "setreg_full": self.setreg_full,
            "setreg_compact": self.setreg_compact,
            "setreg_saved_pct": round(100.0 * (1.0 - self.setreg_compact / self.setreg_full), 2)
            if self.setreg_full else 0.0,
            "avg_words_per_instr": round((compact_bytes / 4) / self.n_instr, 3) if self.n_instr else 0.0,
            "avg_setreg_per_instr": round(self.setreg_compact / self.n_instr, 3) if self.n_instr else 0.0,
        }


def build_compact_program(g, sched) -> CompactProgram:
    records, cores, wave_len, _names = collect(g, sched)
    last_by_core: dict[int, List[int]] = {}
    out_words: List[int] = []
    masks: List[int] = []
    changed_total = 0
    for rec, core in zip(records, cores):
        prev = last_by_core.get(core)
        mask = 0
        vals: List[int] = []
        for r, val in enumerate(rec):
            if prev is None or int(prev[r]) != int(val):
                mask |= (1 << r)
                vals.append(int(val) & 0xFFFFFFFF)
        masks.append(mask)
        changed_total += _popcount(mask)
        header = (int(core) & 0xFF) | ((mask & 0xFFFF) << 8)
        out_words.append(header)
        out_words.extend(vals)
        last_by_core[int(core)] = list(rec)
    raw = b"".join(_u32_bytes(w) for w in out_words)
    n_instr = len(records)
    return CompactProgram(
        raw=raw,
        words=out_words,
        masks=masks,
        cores=cores,
        wave_len=wave_len,
        n_instr=n_instr,
        n_wave=len(wave_len),
        setreg_full=n_instr * isa.NUM_REGS,
        setreg_compact=changed_total,
        full_program_bytes=n_instr * isa.NUM_REGS * 4,
    )


def _c_array(name: str, ctype: str, values: List[int], per_line: int, fmt) -> str:
    body = []
    for i in range(0, len(values), per_line):
        body.append("    " + ", ".join(fmt(v) for v in values[i:i + per_line]) + ",")
    return f"static const {ctype} {name}[{len(values)}] = {{\n" + "\n".join(body) + "\n};"


def emit_firmware_compact(g, sched, *, model="model", mode="hbm",
                          core_stride: int = isa.DEFAULT_CORE_STRIDE,
                          prog_base: int = COMPACT_PROG_BASE) -> Tuple[str, CompactProgram]:
    """Return (C source, compact_program).  mode='hbm' or 'embed'."""
    cp = build_compact_program(g, sched)
    n_cores = sched.n_cores
    L: List[str] = []
    L.append("#include <stdint.h>")
    L.append("/* generated by llmc compact-delta firmware codegen */")
    L.append(f"/* model={model} cores={n_cores} instrs={cp.n_instr} waves={cp.n_wave} mode={mode} */")
    L.append("")
    L.append(f"#define MMIO_BASE   0x{isa.MMIO_BASE:08X}u")
    L.append(f"#define CORE_STRIDE 0x{core_stride:X}u")
    L.append(f"#define R_STATUS    {isa.REG_NAMES.index('PARA_CONFIG')}u")
    L.append("#define DONE_MASK   0x7u")
    L.append("#define DONE_VAL    0x4u")
    L.append(f"#define N_WAVE      {cp.n_wave}u")
    L.append(f"#define MAX_CORES   {max(1, n_cores)}u")
    if mode == "hbm":
        L.append("")
        L.append("/* RV32 note: use an address aperture if raw HBM addresses are not directly pointer-addressable. */")
        L.append(f"#define PROG_BASE   0x{prog_base:X}ULL")
    L.append("")
    L.append("#define SetReg(a,v) (*(volatile uint32_t*)(uintptr_t)(a) = (uint32_t)(v))")
    L.append("#define ReadReg(a)  (*(volatile uint32_t*)(uintptr_t)(a))")
    L.append("")
    L.append(_c_array("wave_len", "uint8_t", cp.wave_len, 32, lambda v: str(v)))
    L.append("")
    if mode == "embed":
        L.append(_c_array("compact_prog", "uint32_t", cp.words, 8, lambda v: f"0x{v:08X}u"))
        L.append("")
    L.append("static void wait_done(uint32_t c){")
    L.append("    uint32_t base = MMIO_BASE + c*CORE_STRIDE;")
    L.append("    while ((ReadReg(base + 4u*R_STATUS) & DONE_MASK) != DONE_VAL) { }")
    L.append("}")
    L.append("")
    L.append("int main(void){")
    if mode == "hbm":
        L.append("    const volatile uint32_t *p = (const volatile uint32_t*)(uintptr_t)PROG_BASE;")
    else:
        L.append("    const uint32_t *p = compact_prog;")
    L.append("    for (uint32_t w = 0; w < N_WAVE; w++){")
    L.append("        uint32_t used[MAX_CORES]; uint32_t nu = 0;")
    L.append("        for (uint32_t j = 0, wl = wave_len[w]; j < wl; j++){")
    L.append("            uint32_t hdr = *p++;")
    L.append("            uint32_t c = hdr & 0xFFu;")
    L.append("            uint32_t mask = (hdr >> 8) & 0xFFFFu;")
    L.append("            uint32_t base = MMIO_BASE + c*CORE_STRIDE;")
    L.append("            for (uint32_t r = 0; r < 16u; r++){")
    L.append("                if (mask & (1u << r)) SetReg(base + 4u*r, *p++);")
    L.append("            }")
    L.append("            used[nu++] = c;")
    L.append("        }")
    L.append("        for (uint32_t k = 0; k < nu; k++) wait_done(used[k]);")
    L.append("    }")
    L.append("    return 0;")
    L.append("}")
    return "\n".join(L) + "\n", cp


def write_compact_artifacts(g, sched, outdir: str, *, model="model", mode="hbm",
                            core_stride: int = isa.DEFAULT_CORE_STRIDE) -> dict:
    os.makedirs(outdir, exist_ok=True)
    c_src, cp = emit_firmware_compact(g, sched, model=model, mode=mode, core_stride=core_stride)
    with open(os.path.join(outdir, "firmware_compact.c"), "w") as f:
        f.write(c_src)
    with open(os.path.join(outdir, "program_compact.bin"), "wb") as f:
        f.write(cp.raw)
    stats = cp.stats()
    with open(os.path.join(outdir, "compact_stats.json"), "w") as f:
        json.dump(stats, f, indent=2)
    return stats


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate compact-delta firmware + HBM program stream.")
    ap.add_argument("--model", choices=list(PRESETS), default="qwen")
    ap.add_argument("--tokens", type=int, default=64)
    ap.add_argument("--cores", type=int, default=1)
    ap.add_argument("--strategy", choices=["single", "round_robin", "critical"], default="critical")
    ap.add_argument("--layers", type=int, default=None)
    ap.add_argument("--mlp-only", action="store_true")
    ap.add_argument("--mode", choices=["hbm", "embed"], default="hbm")
    ap.add_argument("--core-stride", type=lambda s: int(s, 0), default=isa.DEFAULT_CORE_STRIDE)
    ap.add_argument("-o", "--out", default="out_compact")
    args = ap.parse_args(argv)
    g = build_graph(args.model, token_num=args.tokens, n_layers=args.layers, mlp_only=args.mlp_only)
    sched = Scheduler(g, n_cores=args.cores, strategy=args.strategy).schedule()
    backend.allocate(g, sched)
    stats = write_compact_artifacts(g, sched, args.out, model=args.model, mode=args.mode,
                                    core_stride=args.core_stride)
    print(f"wrote {args.out}/firmware_compact.c + program_compact.bin")
    print(json.dumps(stats, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
