#!/usr/bin/env python3
"""
emit_firmware.py -- generate control-core firmware as a small *interpreter*
instead of fully-unrolled SetReg code.

The unrolled `emit_c` bakes every one of N*16 MMIO writes into straight-line
code, so `.text` grows with the model and overflows IMEM. Here the firmware is a
fixed ~40-line loop that walks the instruction image; `.text` is *constant*
(~1-2 KB) regardless of model size. The per-op instruction words become *data*:

  --mode embed  : words live in a `const uint32_t prog[N][16]` (rodata/DMEM).
                  Correct on bare rv32; footprint = N*64 B of rodata.
  --mode hbm    : words stay in HBM (the program.bin you already DMA to
                  INSTR_BASE); the loop loads them. Smallest footprint, but on
                  rv32/ilp32 the HBM base must be reachable as a 32-bit pointer
                  (an aperture window) -- see the PROG_BASE warning in the C.

Only a tiny schedule descriptor is ever in rodata: one core-id byte per op and
one length byte per wave (wave widths are <= #cores <= 8). With --dedup, a
16-bit per-op write-mask is added so the loop writes only the registers that
changed since that core's previous op (configuration registers retain their
values), cutting runtime MMIO writes.

Usage:
  python emit_firmware.py --model qwen --tokens 64 --cores 4 --mode embed -o out/
  python emit_firmware.py --model qwen --tokens 64 --cores 8 --mode hbm --dedup -o out/

Drop-in: the core routine is `emit_firmware_interp(graph, schedule, ...)`; it is
self-contained and can be pasted next to `emit_c` in backend.py.
"""
from __future__ import annotations

import argparse
import os
from typing import List, Tuple

from llmc.models import build_graph, PRESETS
from llmc.schedule import Scheduler
from llmc import backend, isa

INSTR_BASE = 0x4000000000           # where program.bin is DMA'd (HBM0_PC0)


# --------------------------------------------------------------------------- #
def collect(g, sched) -> Tuple[List[List[int]], List[int], List[int], List[str]]:
    """Flatten the schedule into per-instruction words / core-id / wave lengths."""
    words: List[List[int]] = []
    cores: List[int] = []
    wave_len: List[int] = []
    names: List[str] = []
    for wave in sched.waves:
        wave_len.append(len(wave))
        for op_i, core in wave:
            inst = backend.lower_op(g, g.ops[op_i])
            words.append(list(inst.words))
            cores.append(int(core))
            names.append(g.ops[op_i].name)
    return words, cores, wave_len, names


def write_masks(words: List[List[int]], cores: List[int]) -> Tuple[List[int], int, int]:
    """16-bit mask per instruction: bit r set if reg r differs from this core's
    previous instruction (registers persist, so unchanged writes are skippable)."""
    last = {}                       # core -> last 16 words written
    masks: List[int] = []
    total = changed = 0
    for w, c in zip(words, cores):
        prev = last.get(c)
        m = 0
        for r in range(16):
            total += 1
            if prev is None or prev[r] != w[r]:
                m |= (1 << r)
                changed += 1
        masks.append(m)
        last[c] = w
    return masks, total, changed


def _c_array(name: str, ctype: str, values: List[int], per_line: int, fmt) -> str:
    body = []
    for i in range(0, len(values), per_line):
        body.append("    " + ", ".join(fmt(v) for v in values[i:i + per_line]) + ",")
    return f"static const {ctype} {name}[{len(values)}] = {{\n" + "\n".join(body) + "\n};"


def emit_firmware_interp(g, sched, *, model="model", mode="embed", dedup=False,
                         core_stride: int = 0x1000) -> Tuple[str, dict]:
    words, cores, wave_len, names = collect(g, sched)
    n_instr, n_wave = len(words), len(wave_len)
    n_cores = sched.n_cores
    masks, total_w, changed_w = write_masks(words, cores)

    L: List[str] = []
    L.append("#include <stdint.h>")
    L.append("/* generated by llmc interpreter codegen -- constant .text, "
             f"data-driven ({mode}{', dedup' if dedup else ''}) */")
    L.append(f"/* model={model}  cores={n_cores}  instrs={n_instr}  waves={n_wave} */")
    L.append("")
    L.append(f"#define MMIO_BASE   0x{isa.MMIO_BASE:08X}u")
    L.append(f"#define CORE_STRIDE 0x{core_stride:X}u")
    L.append("#define NUM_REGS    16u")
    L.append(f"#define R_STATUS    {isa.REG_NAMES.index('PARA_CONFIG')}u   /* PARA_CONFIG */")
    L.append("#define DONE_MASK   0x7u")
    L.append("#define DONE_VAL    0x4u")
    L.append(f"#define N_INSTR     {n_instr}u")
    L.append(f"#define N_WAVE      {n_wave}u")
    L.append(f"#define MAX_CORES   {max(1, n_cores)}u")
    if mode == "hbm":
        L.append("")
        L.append("/* WARNING (rv32/ilp32): a raw 0x4000000000 HBM address does NOT")
        L.append(" * fit a 32-bit pointer and will truncate. Set PROG_BASE to the")
        L.append(" * low-mapped aperture window that aliases the instruction image,")
        L.append(" * or use --mode embed. */")
        L.append(f"#define PROG_BASE   0x{INSTR_BASE:X}ULL")
    L.append("")
    L.append("#define SetReg(a,v) (*(volatile uint32_t*)(uintptr_t)(a) = (uint32_t)(v))")
    L.append("#define ReadReg(a)  (*(volatile uint32_t*)(uintptr_t)(a))")
    L.append("")

    # schedule descriptor (always small)
    L.append(_c_array("instr_core", "uint8_t", cores, 32, lambda v: str(v)))
    L.append("")
    L.append(_c_array("wave_len", "uint8_t", wave_len, 32, lambda v: str(v)))
    L.append("")
    if dedup:
        L.append(_c_array("instr_mask", "uint16_t", masks, 16, lambda v: f"0x{v:04X}"))
        L.append("")
    if mode == "embed":
        rows = ["    {" + ",".join(f"0x{w:08X}" for w in rec) + "}," for rec in words]
        L.append(f"static const uint32_t prog[N_INSTR][NUM_REGS] = {{\n" +
                 "\n".join(rows) + "\n};")
        L.append("")

    L.append("static void wait_done(uint32_t c){")
    L.append("    uint32_t base = MMIO_BASE + c*CORE_STRIDE;")
    L.append("    while ((ReadReg(base + 4u*R_STATUS) & DONE_MASK) != DONE_VAL) { }")
    L.append("}")
    L.append("")
    L.append("int main(void){")
    if mode == "hbm":
        L.append("    const volatile uint32_t *prog ="
                 " (const volatile uint32_t*)(uintptr_t)PROG_BASE;")
    L.append("    uint32_t i = 0;")
    L.append("    for (uint32_t w = 0; w < N_WAVE; w++){")
    L.append("        uint32_t used[MAX_CORES]; uint32_t nu = 0;")
    L.append("        for (uint32_t j = 0, wl = wave_len[w]; j < wl; j++, i++){")
    L.append("            uint32_t c = instr_core[i];")
    L.append("            uint32_t base = MMIO_BASE + c*CORE_STRIDE;")
    if mode == "embed":
        L.append("            const uint32_t *rec = prog[i];")
    else:
        L.append("            const volatile uint32_t *rec = prog + (uint32_t)i*NUM_REGS;")
    if dedup:
        L.append("            uint32_t m = instr_mask[i];")
        L.append("            for (uint32_t r = 0; r < NUM_REGS; r++)")
        L.append("                if (m & (1u << r)) SetReg(base + 4u*r, rec[r]);")
    else:
        L.append("            for (uint32_t r = 0; r < NUM_REGS; r++)")
        L.append("                SetReg(base + 4u*r, rec[r]);")
    L.append("            used[nu++] = c;")
    L.append("        }")
    L.append("        for (uint32_t k = 0; k < nu; k++) wait_done(used[k]);")
    L.append("    }")
    L.append("    return 0;")
    L.append("}")

    rodata = len(cores) + len(wave_len) + (2 * len(masks) if dedup else 0)
    embed_bytes = n_instr * 64 if mode == "embed" else 0
    stats = {
        "mode": mode, "dedup": dedup, "n_instr": n_instr, "n_wave": n_wave,
        "schedule_rodata_bytes": rodata,
        "embedded_prog_bytes": embed_bytes,
        "hbm_prog_bytes": 0 if mode == "embed" else n_instr * 64,
        "setreg_full": total_w, "setreg_dedup": changed_w,
        "setreg_saved_pct": round(100 * (1 - changed_w / total_w), 1) if total_w else 0,
    }
    return "\n".join(L) + "\n", stats


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", choices=list(PRESETS), default="qwen")
    ap.add_argument("--tokens", type=int, default=64)
    ap.add_argument("--cores", type=int, default=1)
    ap.add_argument("--strategy", choices=["single", "round_robin", "critical"],
                    default="critical")
    ap.add_argument("--layers", type=int, default=None)
    ap.add_argument("--mlp-only", action="store_true")
    ap.add_argument("--mode", choices=["embed", "hbm"], default="embed")
    ap.add_argument("--dedup", action="store_true",
                    help="emit per-op write-mask; write only changed registers")
    ap.add_argument("--core-stride", type=lambda s: int(s, 0), default=0x1000)
    ap.add_argument("-o", "--out", default="out_interp")
    args = ap.parse_args(argv)

    os.makedirs(args.out, exist_ok=True)
    g = build_graph(args.model, token_num=args.tokens, n_layers=args.layers,
                    mlp_only=args.mlp_only)
    sched = Scheduler(g, n_cores=args.cores, strategy=args.strategy).schedule()
    backend.allocate(g, sched)
    c_src, stats = emit_firmware_interp(g, sched, model=args.model, mode=args.mode,
                                        dedup=args.dedup, core_stride=args.core_stride)
    raw, _, _ = backend.emit_bin(g, sched)

    with open(os.path.join(args.out, "firmware_interp.c"), "w") as f:
        f.write(c_src)
    with open(os.path.join(args.out, "program.bin"), "wb") as f:
        f.write(raw)

    print(f"wrote {args.out}/firmware_interp.c  +  program.bin")
    print(f"  instrs={stats['n_instr']}  waves={stats['n_wave']}  mode={stats['mode']}")
    print(f"  schedule rodata : {stats['schedule_rodata_bytes']:,} B")
    if stats["embedded_prog_bytes"]:
        print(f"  embedded prog   : {stats['embedded_prog_bytes']:,} B (rodata/DMEM)")
    else:
        print(f"  HBM prog image  : {stats['hbm_prog_bytes']:,} B (stays in HBM)")
    print(f"  SetReg writes   : {stats['setreg_full']:,} full"
          + (f"  ->  {stats['setreg_dedup']:,} with dedup "
             f"(-{stats['setreg_saved_pct']}%)" if args.dedup else
             f"  (dedup would cut to {stats['setreg_dedup']:,}, "
             f"-{stats['setreg_saved_pct']}%)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())